theme: minima

github_username: selber-ausmalen
email: info@selber-ausmalen.de
description: Selber kreativ gestalten

title: selber-ausmalen.de

header_pages:
  - design.md
  - color.md
  - shop.md
  - about.md

plugins:
  - "jekyll-github-metadata"