theme: minima

github_username: selber-ausmalen
email: info@selber-ausmalen.de
description: Selber kreativ gestalten

baseurl: selber-ausmalen.github.io

title: selber-ausmalen.de

header_pages:
  - design.md
  - color.md
  - shop.md
  - about.md
