theme: minima

github_username: selber-ausmalen
pinterest_username: selber_ausmalen
# facebook_username: selber-ausmalen.de

email: info@selber-ausmalen.de
description: freie - CC BY-SA 4.0 - Vorlagen zum Ausdrucken und selber Ausmalen

title: selber-ausmalen.de

header_pages:
  - design.md
  - color.md
  - shop.md
  - about.md

plugins:
  - "jekyll-github-metadata"

repository: selber-ausmalen/selber-ausmalen.github.io

google_analytics: UA-167429523-1
